# Use a base image with JDK 17 installed
FROM openjdk:17-jdk-slim

# Create a working directory for the app
WORKDIR /app

# Copy the JAR file generated by Maven into the Docker image
# Make sure to use the correct JAR file name, replacing `food-delivery-app-1.0.0.jar` if necessary
ARG JAR_FILE=target/repas-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

# Expose the port the app will run on
EXPOSE 8080

# Command to run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
